script: |
  set -euo pipefail
  cd /home/ecs-user/Media360-React

  echo "[INFO] START DEPLOY"
  pwd
  ls -la

  git pull origin main

  echo "[INFO] Installing..."
  npm install --legacy-peer-deps

  echo "[INFO] Building..."
  npm run build

  echo "[INFO] DONE"